services:
    mongodb:
        image: mongo
        container_name: mongo-chatbot
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: fvaquiro
            MONGO_INITDB_ROOT_PASSWORD: i5VMT2x6Gfd6V0c7
        ports:
            - "27017:27017"
        volumes:
            - ./mongo-data:/data/db

volumes:
    mongo-data:
        driver: local